import React from 'react'
export const dynamic = 'force-static';
import Nav from '../Nav/Nav'
import Image from 'next/image';
import Storedownload from '../Images/Download/Storedownload.webp'
import IOSRecomm from '../Images/Download/IOSRecomm.svg'
import DownloadBIcon from '../Images/Download/DownloadBIcon.svg'
import features from '../Images/Download/features.svg'
import Member from '../Images/Download/Member.svg'
import View from '../Images/Download/View.svg'
import Coin from '../Images/Download/Coin.svg'
import user from '../Images/Download/user.svg'
import transfer from '../Images/Download/transfer.svg'
import DownloadImageSwitcher from './DownloadImageSwitcher';
import Footer from '../Footer/Footer'

export const metadata = {
  title: "membersgram | Download",
  description: "Generated by create next app",
};

const Download = () => {

  return (
    <div className="w-full h-screen">
      <Nav />
      <div className="w-full h-screen flex flex-col justify-start items-center" >



        <div className="w-full flex flex-col md:flex-row  m-auto mt-[72px] justify-start items-center md:pl-[100]">
          <div className="w-[100%] flex flex-row  mx-auto justify-center items-center md:justify-center">
           <DownloadImageSwitcher />
         
          </div>
          <div className="w-[90%] md:w-[100%] mt-[1rem] m-auto md:m-0">
            <h1 className="text-[30px] m-auto font-medium w-[80%] md:w-[50%] md:m-0">Free download of Membergram is available on the
              <a
                className='text-[#2196f3] px-1 '

                href="https://play.google.com/store/apps/details?id=gram.members.android">
                Play Store
              </a>
              or via direct link
            </h1>
            <h2 className="mt-[24px] text-[16px] w-[80%] md:w-[50%] m-auto md:m-0">
              Take your Telegram channel and group to the next level! Download Membersgram and start growing with real members and better engagement.
            </h2>
            <div className="mt-[32px] m-auto flex flex-col md:flex-row  mx-auto justify-start items-start">
              <div className="flex flex-col  ">

                <button className="bg-[#1976d2] rounded-[33px] text-[#fff] py-[12px] 
                px-[18px] mr-1.5 text-[16px] 
                font-medium "
                //  onClick="window.location.href='https://webapp.membersgram.com/'"
                 >Use the Web App</button>
                <div className="flex flex-row items-center justify-start text-[12px] text-[#2196f3] ">
                  <Image
                    src={IOSRecomm}
                    alt="Storedownload"
                    className="w-[24px] h-[24px] flex flex-row items-center ml-1 mr-1"
                    loading="lazy"
                  />
                  Recommend for iOS users
                </div>
              </div>

              <button className="flex 
              flex-row justify-center h-[48px] w-fit
              items-center
              mt-[16px]
              md:mt-[0]
               bg-[#fff] 
               rounded-[33px] text-[#1976d2] 
               py-[14px] px-[24px] border-[1px] text-[16px] font-medium"
                // onclick="window.location.href='https://membersgram.com/MembersgramApp/membersgram.apk'"
                >
                <Image
                  src={DownloadBIcon}
                  alt="Storedownload"
                  className="w-[24px] h-[24px] mr-1"
                  loading="lazy"
                />
                Install android app</button>

            </div>


            <h3 className="mt-[48px] font-medium text-[16px]">Latest features in membersgram</h3>


            {/* item1 */}
            <div className="mt-[24px] flex flex-row justify-start items-start">
              <div className="">
                <Image
                  src={features}
                  alt="Storedownload"
                  className="w-fit h-fit mr-[16px]"
                  loading="lazy"
                />
              </div>
              <div className="FeaturesItemTeXts">
                <div className="text-[16px] font-normal">
                  Play Games
                </div>

                <div className="text-[14px] font-normal mt-[8px]">
                  win coins, and Get Telegram members and views with coins
                </div>
              </div>
            </div>
            {/* item2 */}
            <div className="mt-[24px] flex flex-row justify-start items-start">
              <div className="">
              <Image
                  src={features}
                  alt="Storedownload"
                  className="w-fit h-fit mr-[16px]"
                  loading="lazy"
                />
              </div>
              <div className="FeaturesItemTeXts">
                <div className="text-[16px] font-normal">
                  Sell accounts on Web App
                </div>

                <div className="text-[14px] font-normal mt-[8px] mask-linear-to-white w-55">
                  earn coins, and instantly boost your Telegram groups and channel with members and views
                </div>
              </div>
            </div>



          </div>
        </div>
        {/* boxes */}
        <div className="flex flex-col md:flex-row justify-between items-center my-[56px] md:items-center gap-4 grow w-full md:w-200  m-auto h-fit ">


          <div className="flex
           flex-col 
           justify-center items-center
           px-[32px] py-[14px]
           w-[203px] h-[195px] 
           border-[1px] border-[#DADADA] text-[14px] rounded-[12px]">
            <div className="BottomBoxDownloadImage">
              <Image
                src={Member}
                alt="Storedownload"
                className="w-fit h-fit"
                loading="lazy"
              />
            </div>
            <div className="text-center mt-[20px] flex flex-row justify-center items-center">
              You can easily increase the members of your channel/group
            </div>
          </div>

          <div className="flex
           flex-col 
           justify-center items-center
           px-[32px] py-[14px]
           w-[203px] h-[195px] 
           border-[1px] border-[#DADADA] text-[14px] rounded-[12px]">
            <div className="BottomBoxDownloadImage">
              <Image
                src={View}
                alt="Storedownload"
                className="w-fit h-fit"
                loading="lazy"
              />
            </div>
            <div className="text-center mt-[20px] flex flex-row justify-center items-center">
             {"Boost your channel's visibility by ordering views for your posts!"} 
            </div>
          </div>
          <div className="flex
           flex-col 
           justify-center items-center
           px-[32px] py-[14px]
           w-[203px] h-[195px] 
           border-[1px] border-[#DADADA] text-[14px] rounded-[12px]">
            <div className="BottomBoxDownloadImage">
              <Image
                src={Coin}
                alt="Storedownload"
                className="w-fit h-fit"
                loading="lazy"
              />
            </div>
            <div className="text-center mt-[20px] flex flex-row justify-center items-center">
              You can get coins for free and order member and view with coins
            </div>
          </div>
          <div className="flex
           flex-col 
           justify-center items-center
           px-[32px] py-[14px]
           w-[203px] h-[195px] 
           border-[1px] border-[#DADADA] text-[14px] rounded-[12px]">
            <div className="BottomBoxDownloadImage">
              <Image
                src={user}
                alt="Storedownload"
                className="w-fit h-fit"
                loading="lazy"
              />
            </div>
            <div className="text-center mt-[20px] flex flex-row justify-center items-center">
              You can create several accounts and get free coins with each one
            </div>
          </div>
          <div className="flex
           flex-col 
           justify-center items-center
           px-[32px] py-[14px]
           w-[203px] h-[195px] 
           border-[1px] border-[#DADADA] text-[14px] rounded-[12px]">
            <div className="BottomBoxDownloadImage">
              <Image
                src={transfer}
                alt="Storedownload"
                className="w-fit h-fit"
                loading="lazy"
              />

            </div>
            <div className="text-center mt-[20px] flex flex-row justify-center items-center">
              You can transfer coins from any account to another account
            </div>
          </div>

        </div>

          <Footer />


      </div>
    </div>
  )
}

export default Download