import React from 'react';
import { Button } from '../components/ui/button';
// import { Card, CardContent } from '@/components/ui/card';
// import { Badge } from '../components/ui/badge';
import { Download, Smartphone, Shield, Zap, Users, Star, ExternalLink, Play } from 'lucide-react';
import { Bot, BarChart3, Target } from 'lucide-react';
import Navigation from '../components/Navigation';
// import { useTranslations } from 'next-intl';
// import Link from 'next/link';

export const metadata = {
  title: "membersgram | Download",
  description: "Generated by create next app",
};

const Index = () => {
  const features = [

    {
      icon: Smartphone,
      bg:'bg-purple-100',
      color: ' text-purple-600',
      title: 'Targeted Campaigns',
      description: 'Create and manage targeted marketing campaigns to attract your ideal audience.'
    },
    {
      icon: Zap,
      bg:'bg-blue-100',
      color: ' text-blue-600',
      title: 'Automation Tools',
      description: 'Automate welcome messages, member verification, and content scheduling.'
    },
    {
      icon: Shield,
      bg:'bg-green-100',
      color: ' text-green-600',
      title: 'Safety & Compliance',
      description: 'Built-in spam protection and compliance tools to keep your channel secure.'
    },

  ];

  // const t = useTranslations();
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-white">
      <Navigation />


      {/* Hero Section */}
      <section className="container mx-auto px-6 py-20">
        <div className="grid lg:grid-cols-2 gap-12 items-center">
          <div className="space-y-8">
            <div className="space-y-4">
              <div className="bg-blue-100 text-blue-800 hover:bg-blue-100 w-fit p-2 rounded-2xl">
              #1 Telegram Growth Tool
              </div>
         
              <div className="flex gap-4">
            
              </div>
              <h1 className="text-5xl lg:text-6xl font-bold text-gray-900 leading-tight">
                Grow Your
                <span className="text-blue-600 block">Telegram Channel</span>
                Effortlessly
              </h1>
              <p className="text-xl text-gray-600 leading-relaxed">
                Boost your Telegram channel with real members, advanced analytics, and powerful automation tools.
                Join thousands of creators who trust Membersgram for organic growth.
              </p>
            </div>

            {/* CTA Buttons */}
            <div id="download" className="space-y-4">
              <div className="flex flex-col sm:flex-row gap-4">
                <Button size="lg" className="bg-blue-600 flex flex-row items-center hover:bg-blue-700 text-white px-8 py-1 text-lg">
                  <Play className="w-5 h-5 mr-2" />
                  Google Play Store
                </Button>
                <Button size="lg" variant="outline" className="border-blue-600 flex flex-row items-center  text-blue-600 hover:bg-blue-50 px-8 py-4 text-lg">
                  <Download className="w-5 h-5 mr-2" />
                  Direct APK Download
                </Button>
              </div>
              <Button size="lg" variant="ghost" className="text-blue-600 flex flex-row items-center hover:bg-blue-50 w-full sm:w-auto">
                <ExternalLink className="w-5 h-5 mr-2" />
                Try Web App Version
              </Button>
            </div>

            {/* Social Proof */}
            <div className="flex items-center space-x-6 pt-4">
              <div className="text-center">
                <div className="text-3xl font-bold text-gray-900">50K+</div>
                <div className="text-sm text-gray-600">Active Users</div>
              </div>
              <div className="text-center">
                <div className="text-3xl font-bold text-gray-900">1M+</div>
                <div className="text-sm text-gray-600">Members Grown</div>
              </div>
              <div className="flex items-center">
                <div className="flex text-yellow-400">
                  {[...Array(5)].map((_, i) => (
                    <Star key={i} className="w-5 h-5 fill-current" />
                  ))}
                </div>
                <span className="ml-2 text-sm text-gray-600">4.9/5 Rating</span>
              </div>
            </div>
          </div>

          {/* Phone Mockup */}
          <div className="relative">
            <div className="relative mx-auto w-80 h-96">
              <div className="absolute inset-0 bg-gradient-to-r from-blue-400 to-blue-600 rounded-3xl transform rotate-6 opacity-20"></div>
              <div className="relative bg-gray-900 rounded-3xl p-2 shadow-2xl">
                <div className="bg-gray-100 rounded-2xl h-full p-6 flex flex-col">
                  <div className="flex items-center justify-between mb-6">
                    <div className="w-3 h-3 bg-red-400 rounded-full"></div>
                    <div className="w-3 h-3 bg-yellow-400 rounded-full"></div>
                    <div className="w-3 h-3 bg-green-400 rounded-full"></div>
                  </div>
                  <div className="flex-1 space-y-4">
                    <div className="bg-blue-600 text-white p-4 rounded-lg">
                      <div className="text-sm font-semibold">Channel Growth</div>
                      <div className="text-2xl font-bold">+2,847</div>
                      <div className="text-xs opacity-90">New members today</div>
                    </div>
                    <div className="space-y-2">
                      <div className="h-3 bg-blue-200 rounded-full overflow-hidden">
                        <div className="h-full bg-blue-600 rounded-full" style={{ width: '75%' }}></div>
                      </div>
                      <div className="text-xs text-gray-600">Growth target: 75% complete</div>
                    </div>
                    <div className="grid grid-cols-2 gap-2">
                      <div className="bg-white p-3 rounded-lg text-center">
                        <div className="text-lg font-bold text-blue-600">98%</div>
                        <div className="text-xs text-gray-600">Real Users</div>
                      </div>
                      <div className="bg-white p-3 rounded-lg text-center">
                        <div className="text-lg font-bold text-green-600">24/7</div>
                        <div className="text-xs text-gray-600">Active</div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section id="features" className="py-20 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-5xl font-bold text-gray-900 mb-4">
              Everything You Need to{' '}
              <span className="text-blue-600">Scale Fast</span>
            </h2>
            <p className="text-xl text-gray-600 max-w-3xl mx-auto">
              Comprehensive tools designed specifically for Telegram growth and community management.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <div
                key={index}
                className="bg-white rounded-xl p-8 shadow-lg hover:shadow-xl transition-shadow duration-300 group"
              >
                {/* <div className="w-16 h-16 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-6">
                  <Zap className="w-8 h-8 text-blue-600" />
                </div> */}
                <div className={` ${feature.bg} w-16 h-16  rounded-full flex items-center justify-center mx-auto mb-6`}>
                  <feature.icon className={`${feature.color} h-6 w-6 text-blue-600`} />
                </div>
                <h3 className="text-xl font-bold text-gray-900 mb-4 text-center">
                  {feature.title}
                </h3>
                <p className="text-gray-600 leading-relaxed text-center">
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>


    


      {/* Footer */}
      <footer id="contact" className="bg-gray-900 py-12">
        <div className="container mx-auto px-6">
          <div className="grid md:grid-cols-4 gap-8">
            <div className="col-span-2">
              <div className="flex items-center space-x-2 mb-4">
                <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center">
                  <Users className="w-5 h-5 text-white" />
                </div>
                <span className="text-xl font-bold text-white">Membersgram</span>
              </div>
              <p className="text-gray-400 max-w-md">
                The ultimate Telegram channel growth platform. Grow your audience
                safely and effectively with our proven methods.
              </p>
            </div>

            <div>
              <h4 className="text-white font-semibold mb-4">Legal</h4>
              <div className="space-y-2">
                <a href="#" className="text-gray-400 hover:text-white transition-colors block">Privacy Policy</a>
                <a href="#" className="text-gray-400 hover:text-white transition-colors block">Terms of Use</a>
                <a href="#" className="text-gray-400 hover:text-white transition-colors block">GDPR Compliance</a>
              </div>
            </div>

            <div>
              <h4 className="text-white font-semibold mb-4">Contact</h4>
              <div className="space-y-2">
                <a href="#" className="text-gray-400 hover:text-white transition-colors block">Support Center</a>
                <a href="#" className="text-gray-400 hover:text-white transition-colors block">Contact Us</a>
                <a href="#" className="text-gray-400 hover:text-white transition-colors block">FAQ</a>
              </div>
            </div>
          </div>

          <div className="border-t border-gray-800 mt-8 pt-8 text-center">
            <p className="text-gray-400">
              © 2024 Membersgram. All rights reserved. Built with ❤️ for Telegram creators.
            </p>
          </div>
        </div>
      </footer>
    </div>
  )
}

export default Index