// 'use client';
// export const dynamicSetting  = 'force-static';

import React from "react";
import dynamic from 'next/dynamic';
import Image from "next/image";
const Nav = dynamic(() => import('./Nav/Nav'), {
  ssr: true,  
  loading: () => <p>Loading...</p>,
})
const Footer = dynamic(() => import('./Footer/Footer'), {
  // ssr: false, // فقط در کلاینت رندر میشه
  loading: () => <p>Loading...</p>,
})

// import AOSWrapper from './LandingComponents/AOSWrapper';
// import FaqAccordion from './LandingComponents/FaqAccordion';
// import LandingImageSwitcher from './LandingComponents/LandingImageSwitcher';
const AOSWrapper = dynamic(() => import('./LandingComponents/AOSWrapper'))
const FaqAccordion = dynamic(() => import('./LandingComponents/FaqAccordion'))
const LandingImageSwitcher = dynamic(() => import('./LandingComponents/LandingImageSwitcher'))



// import Nav from './Nav/Nav'
// import Footer from './Footer/Footer'
import User from './Images/Landing/member.png'
import View from './Images/Landing/view.png'
import FreeCoin from './Images/Landing/freecoin.png'
import FreeView from './Images/Landing/freeview.png'

const landingImages = [];

for (let i = 1; i <= 24; i++) {
  landingImages.push(require(`./Images/Landing/${i}.svg`).default);
}

export const metadata = {
  title: "membersgram | Home",
  description: "Generated by create next app",
};
async function getData() {
  return [
    {
      question: "how to increase telegram members?",
      answer: "Choose a Growth Strategy :1- Task-Based Growth : Membersgram allows users to perform tasks like joining other channels/groups to earn points.2- Buy Member Packages : If you prefer quick growth, purchase member packages."
    },
    {
      question: "Is Tailwind customizable?",
      answer: "Yes, Tailwind can be customized using a config file to fit your design system."
    },
    {
      question: "Can I use Tailwind with React?",
      answer: "Absolutely. Tailwind works seamlessly with React and other frameworks."
    }
  ];
}
async function getLogos() {
  return landingImages
}
export default async function Home() {


  const data = await getData();
  const logos = await getLogos();

 
  return (
    <AOSWrapper>
      <div className="w-full h-screen  ">
        <Nav />

        <div className="w-full   flex flex-col overflow-x-hidden
          justify-start 
          item-start 
          mt-[62px] 
          mx-auto" >

          <section data-aos="zoom-in" className="w-full  flex flex-col justify-center item-start mt-[3px] bg-[url('./Images/Landing/bg1.png')]"

          >

            <div className="w-full  max-w-100 m-auto flex flex-col justify-center items-start text-center mt-[32px]">
              <div className="text-[#212121] text-[24px] font-medium">
                Buy Telegram Members | Free Telegram Members
              </div>
              <div className="text-[#212121] text-[16px] font-light text-center max-w-80 m-auto mt-[24px]">
                Order as many members as you want and expand your channel/group
              </div>
              <div className="w-full  flex flex-col justify-between items-center">
                <button className="bg-[#1976D2] text-[#fff] cursor-pointer mt-[19px] text-[17px] font-medium w-[208px] h-[48px] rounded-4xl hover:bg-[#1565C0]">
                  Download app
                </button>
                <button className="bg-[#fff] text-[#1976D2] cursor-pointer text-[17px] mt-[16px] font-medium w-[208px] h-[48px] rounded-4xl border border-[#1976d2] hover:bg-[#D8E3EE] hover:border-transparent">
                  Go to webapp
                </button>
              </div>
            </div>
            <div className="flex flex-row justify-center item-center">
              <LandingImageSwitcher />
            </div>


          </section>

          <section data-aos="zoom-in-up" className="w-full flex flex-col md:flex-row justify-center items-center divide-y md:divide-y-0 md:divide-x divide-gray-300 py-50">
            <div className="text-center px-6 py-4">
              <p className="text-[20px] font-medium text-[#212121]">+2 billion</p>
              <p className="text-[#616161] text-[16px]">Joined members</p>
            </div>
            <div className="text-center px-6 py-4">
              <p className="text-[20px] font-medium text-[#212121]">+7 million</p>
              <p className="text-[#616161] text-[16px]">Number registered</p>
            </div>
            <div className="text-center px-6 py-4">
              <p className="text-[20px] font-medium text-[#212121]">+1.5 million</p>
              <p className="text-[#616161] text-[16px]">Install on Google Play</p>
            </div>
          </section>

          <section data-aos="zoom-in-down" className="w-full h-fit  mx-auto  flex flex-col justify-center items-center bg-[url('./Images/Landing/second.png')] bg-no-repeat bg-bottom  ">
            <h1>
              Why membersgram?
            </h1>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 py-10 max-w-200">
              {/* Item 1 */}
              <div className="flex items-start gap-2">
                <div className="p-2 rounded-md">
                  <Image src={User} alt="member" className="w-[55px] h-[48px]" />
                </div>
                <div className="flex flex-col ">
                  <h3 className="text-[20px]  font-semibold text-gray-800 ">High speed order member</h3>
                  <p className="text-sm text-gray-500">
                    Every day, many users are ready to join your channels/groups
                  </p>
                </div>
              </div>

              {/* Item 2 */}
              <div className="flex items-start gap-2">
                <div className=" p-2 rounded-md">

                  <Image src={View} alt="view" className="w-[55px] h-[48px]" />
                </div>
                <div>
                  <h3 className="text-[20px]  font-semibold text-gray-800">High speed order view</h3>
                  <p className="text-sm text-gray-500">
                    Apply any number of views you want to your posts in a matter of minutes
                  </p>
                </div>
              </div>

              {/* Item 3 */}
              <div className="flex items-start gap-2">
                <div className="p-2 rounded-md">
                  <Image src={FreeView} alt="free view" className="w-[55px] h-[48px]" />
                 
                </div>
                <div>
                  <h3 className="text-[20px]  font-semibold text-gray-800">Free view</h3>
                  <p className="text-sm text-gray-500">
                    With order for the channel, your last 5 posts will be viewed for free
                  </p>
                </div>
              </div>

              {/* Item 4 */}
              <div className="flex items-start gap-2">
                <div className=" p-2 rounded-md">
                  <Image src={FreeCoin} alt="free coins" className="w-[55px] h-[48px]" />

                 
                </div>
                <div>
                  <h3 className="text-[20px] font-semibold text-gray-800">Free coins</h3>
                  <p className="text-[16px] text-gray-500">
                    Joining each channel/group in the app earns you 2 coins
                  </p>
                </div>
              </div>
            </div>

          </section>
          <section data-aos="zoom-in-right" className="text-center w-full h-fit m-auto py-50 ">
            <h1 className="">
              Our customers
            </h1>
            <div className="grid grid-cols-4 max-w-200  m-auto sm:grid-cols-6 md:grid-cols-8 gap-4 bg-white p-4">
              {logos.map((src, index) => (
                <div
                  key={index}
                  className="relative w-16 h-16 sm:w-20 sm:h-20 mx-auto"
                >

                  <Image
                    // ref={imgRef}
                    src={src}
                    alt={`Logo ${index + 1}`}
                    fill
                    loading="lazy"
                    className="object-cover rounded-full "
                  />



                </div>
              ))}
            </div>
          </section>
          <FaqAccordion data={data} />
          <section data-aos="zoom-out-up" className="
          flex flex-row
            justify-center items-center
            text-center 
            m-auto 
            mt-[98px]
            w-full 
            max-w-[1155px]
            bg-[url('./Images/Landing/SectionFiveMobile.webp')] 
            md:bg-[url('./Images/Landing/SectionFive.png')] 
            lg:w-full  
            h-[755px] 
            bg-no-repeat
            bg-bottom md:bg-center
        
        overflow-hidden">
            <div className="   h-[755px]   w-full
        max-w-[1155px]  flex flex-row
        justify-center items-center   text-center ">
              Buy Telegram Members and Views, Add Free Members to Your Channel or Group
            </div>


          </section>
          <Footer />
        </div>

      </div>
    </AOSWrapper>
  );
}
