// "use client"
// import { Button } from "./components/button";
// import FAQ from "./components/FAQ";
// import FAQ from './components/faq';

// import { MoveRight } from "lucide-react";
// import { useState ,useEffect} from 'react';
// import { Menu, X } from 'lucide-react';

// import { motion } from 'framer-motion'
import React from 'react';
import Navigation from './components/Navigation';
import Hero from './components/Hero';
import Features from './components/Features';
import HowItWorks from './components/HowItWorks';
import Pricing from './components/Pricing';
import Testimonials from './components/Testimonials';
// import FAQ from './components/FAQ';
import Footer from './components/Footer';
import MiniBlog from './components/MiniBlog'

export const metadata = {
  title: "membersgram | Home",
  description: "Generated by create next app",
};
export default function HomePage() {

  return (
  <div className="min-h-screen bg-white">
      <Navigation />

     <Hero />  
     
        
      <Features />
      <HowItWorks />
      <Pricing />
      <Testimonials /> 
       {/* <FAQ />  */}
       <MiniBlog />
       <Footer />
    </div>
  );
}
